feat: Add permissions checks
sawyre/docker_init pull request #13
Opened 2024-03-13 13:59 UTC by sawyre

Здравствуйте,
Добавил проверку пользователей. Все тесты добавлю в блоке тестов.

2024-03-18 04:40 UTC, aleksandr-semenov-dbp requested changes

2024-03-18 04:40 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    permission_classes = [IsAdminOrReadOnly]
Теперь мы разрешили неатентифицированым пользователям просмотр данных, это не то что мы хотели ставя IsAuthenticated по умолчанию. Здесь стоит скомбинировать фильтры

2024-03-18 04:40 UTC, aleksandr-semenov-dbp commented on task_manager/permissions.py
> +        if request.method in permissions.SAFE_METHODS:
Все же лучше сделать именно на удаление как было в задании

2024-03-21 14:28 UTC, sawyre commented on main/views.py
> +    permission_classes = [IsAdminOrReadOnly]
Поправил, спасибо

2024-03-21 14:29 UTC, sawyre commented on task_manager/permissions.py
> +        if request.method in permissions.SAFE_METHODS:
Справедливо, спасибо.

2024-03-24 19:38 UTC, aleksandr-semenov-dbp requested changes
Нет, не поняли друг друга. Это какой-то слишком сложный комбайн, таких лучше по возможности избегать. Я подразумевал, что 
1. В задании надо сделать пермишен который не разрешает удалять если не is_staff. Желательно чтобы он больше ничего не делал.
2. Очевидно для применения на вьюсетах его надо как-то скомбинировать с IsAuthenticated, это можно сделать множеством способов (например унаследоваться от IsAuthenticated), но в данном случае я бы предложил воспользоваться тем что permission_classes это список и указать несколько.

2024-03-25 11:32 UTC, sawyre commented
Принял, спасибо, облегчил проверку.
Я думал спросить, нужно ли делать объединенный класс или сделать перечисление разных доступов. Но подумал, что объединенный будет лучше.

2024-04-01 04:10 UTC, aleksandr-semenov-dbp approved these changes

2024-04-01 04:10 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    permission_classes = [IsAuthenticated|AdminModelPermissions]
можно просто указать списком, через запятую

2024-04-02 09:37 UTC, merged