Feature/models
sawyre/docker_init pull request #5
Opened 2024-02-21 09:43 UTC by sawyre

2024-02-26 04:52 UTC, aleksandr-semenov-dbp requested changes

2024-02-26 04:52 UTC, aleksandr-semenov-dbp commented on main/models/task.py
> +            self.Statuses.NEW_TASK: [
если единственная операция которая делается со значениями ключей в этой структуре - проверка на вхождение, то логичнее сделать эти значения set-ами а не списками

2024-02-26 04:52 UTC, aleksandr-semenov-dbp commented on main/models/task.py
> +        REALESED = "released"
typo, в значении - правильное написание

2024-02-26 04:52 UTC, aleksandr-semenov-dbp commented on main/models/task.py
> +        ):
если условие не выполняется видимо должна сигнализироваться какая-то ошибка

2024-02-26 20:07 UTC, sawyre commented on main/models/task.py
> +            self.Statuses.NEW_TASK: [
Спасибо, поправил. 
Я сам себя перемудрил.
Логика была, что в списки из двух элементов найти элемент строки быстрее по спискам, так как при использовании сетов нужно посчитать хеш по строке, потом все равно надо будет ее сравнивать итого всегда O(2*string_length).
А при использовании массива, либо одно сравнение строк, либо два итого вроде быстрее в среднем чем O(2*string_length).

2024-02-26 20:07 UTC, sawyre commented on main/models/task.py
> +        REALESED = "released"
Спасибо, поправил

2024-02-26 20:07 UTC, sawyre commented on main/models/task.py
> +        ):
Добавил ошибку

2024-03-04 04:46 UTC, aleksandr-semenov-dbp approved these changes

2024-03-04 04:46 UTC, aleksandr-semenov-dbp commented on main/models/task.py
> +            self.Statuses.IN_DEVELOPMENT: [self.Statuses.IN_QA],
для единообразия/типизации и здесь set

2024-03-04 09:41 UTC, merged