Add admin panel
sawyre/docker_init pull request #6
Opened 2024-02-25 20:06 UTC by sawyre

Здравствуйте,
Понимаю, что лучше такой колбасы PR не делать, просто задания очень зависимые в коде и нужно было использовать код из предыдущих заданий. Так как при мерже в девелоп, он покажет вообще все изменения за все задания, я решил сделать реквест в ветку с предыдущим заданием, чтобы показались только нужные для задания.
Заранее спасибо за проверку.

2024-02-26 05:41 UTC, aleksandr-semenov-dbp requested changes
PR в предыдущую ветку - абсолютно нормально (и очень удобно для меня)

2024-02-26 05:41 UTC, aleksandr-semenov-dbp commented on main/admin.py
> +    UserAdmin.fieldsets[2][1]["fields"] = UserAdmin.fieldsets[2][1]["fields"] + ("role",)
это очень нечитаемо и может легко сломаться. Если это делать, то надо найти нужный филдсет по его имени.

2024-02-26 05:41 UTC, aleksandr-semenov-dbp commented on main/admin.py
> +    UserAdmin.list_display += ('role',)
Нужно не менять UserAdmin а кастомизировать CustomUserAdmin. Здесь надо писать что-то типа `list_display = UserAdmin.list_display + ('role', )`

2024-02-27 20:29 UTC, sawyre commented on main/admin.py
> +    UserAdmin.fieldsets[2][1]["fields"] = UserAdmin.fieldsets[2][1]["fields"] + ("role",)
Думал, думал, решил все таки просто добавить дополнительный блок для кастомных полей.

2024-02-27 20:29 UTC, sawyre commented on main/admin.py
> +    UserAdmin.list_display += ('role',)
Поправил, спасибо

2024-03-04 04:48 UTC, aleksandr-semenov-dbp approved these changes

2024-03-04 09:41 UTC, merged